export const mockLocations = [
  {
    _id: 'loc_chd_1',
    name: 'Chandigarh — Sector 17 City Hub',
    code: 'IXC',
    address: 'Near Neelam Cinema, Sector 17C',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    pincode: '160017',
    phone: '+91 98765 10001',
    status: 'ACTIVE',
    geo: { lat: 30.7333, lng: 76.7794 },
    note: 'Ideal for city commutes, airport arrivals, and corporate rentals',
  },
  {
    _id: 'loc_khr_1',
    name: 'Kharar — Chandigarh University Hub',
    code: 'KHR',
    address: 'NH-05 Highway, Gharuan (Handover at CU Main Gate)',
    city: 'Kharar',
    state: 'Punjab',
    pincode: '140413',
    phone: '+91 98765 10002',
    status: 'ACTIVE',
    geo: { lat: 30.7499, lng: 76.6411 },
    note: 'Doorstep vehicle handover & return directly at Chandigarh University Main Gate',
  },
];

export const mockStudentGetaways = [
  {
    id: 'trip_1',
    destination: 'Kasauli, HP',
    distance: '58 km from CU',
    driveTime: '1.5 Hours',
    recommendedCar: 'Swift / i20',
    description: 'Perfect 1-day or weekend escape from CU campus to colonial hill town with sunset views.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'trip_2',
    destination: 'Shimla & Chail, HP',
    distance: '115 km from CU',
    driveTime: '3.5 Hours',
    recommendedCar: 'Creta / Thar 4x4',
    description: 'Scenic Himalayan expressway road trip with friends via Solan & timber trail.',
    image: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'trip_3',
    destination: 'Manali & Solang, HP',
    distance: '270 km from CU',
    driveTime: '7 Hours',
    recommendedCar: 'Scorpio-N / Innova',
    description: 'Ultimate semester break road trip through Mandi & Kullu tunnel valley.',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80',
  },
];

export const mockVehicles = [
  {
    _id: 'veh_1',
    make: 'Maruti Suzuki',
    model: 'Swift',
    variant: 'ZXI Plus',
    year: 2023,
    registrationNumber: 'CH01AB1234',
    type: 'HATCHBACK',
    transmission: 'MANUAL',
    fuelType: 'PETROL',
    seats: 5,
    doors: 4,
    baggageCapacity: 2,
    mileage: 15400,
    fuelCapacityLiters: 37,
    currentFuelPercent: 95,
    locationId: 'loc_chd_1',
    location: mockLocations[0],
    pricing: {
      daily: 1800,
      weekly: 11000,
      monthly: 42000,
      extraKmCharge: 12,
      freeKmPerDay: 250,
    },
    securityDeposit: 4000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Bluetooth Audio', 'Touchscreen', 'Airbags', 'ABS with EBD', 'Reverse Parking Sensors', 'Fastag Enabled'],
    color: 'Fire Red',
    averageRating: 4.8,
    reviewCount: 28,
  },
  {
    _id: 'veh_2',
    make: 'Hyundai',
    model: 'i20',
    variant: 'Asta (O)',
    year: 2023,
    registrationNumber: 'CH01AB2345',
    type: 'HATCHBACK',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    seats: 5,
    doors: 4,
    baggageCapacity: 2,
    mileage: 18200,
    fuelCapacityLiters: 37,
    currentFuelPercent: 80,
    locationId: 'loc_chd_1',
    location: mockLocations[0],
    pricing: {
      daily: 2200,
      weekly: 13500,
      monthly: 48000,
      extraKmCharge: 14,
      freeKmPerDay: 250,
    },
    securityDeposit: 5000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Sunroof', 'Wireless Apple CarPlay', 'Cruise Control', 'Bose Premium Audio', 'Wireless Charger'],
    color: 'Polar White',
    averageRating: 4.9,
    reviewCount: 34,
  },
  {
    _id: 'veh_3',
    make: 'Mahindra',
    model: 'Thar',
    variant: 'LX 4x4 Hard Top',
    year: 2023,
    registrationNumber: 'PB65EF6789',
    type: 'SUV',
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    seats: 4,
    doors: 3,
    baggageCapacity: 2,
    mileage: 19500,
    fuelCapacityLiters: 57,
    currentFuelPercent: 85,
    locationId: 'loc_khr_1',
    location: mockLocations[1],
    pricing: {
      daily: 4200,
      weekly: 26000,
      monthly: 96000,
      extraKmCharge: 18,
      freeKmPerDay: 250,
    },
    securityDeposit: 10000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['True 4x4 Low Ratio (Shimla/Manali Ready)', 'Convertible/Hard Top', 'Off-road Telematics', 'Roll Cage'],
    color: 'Rocky Beige',
    averageRating: 5.0,
    reviewCount: 46,
  },
  {
    _id: 'veh_4',
    make: 'Hyundai',
    model: 'Creta',
    variant: 'SX (O)',
    year: 2023,
    registrationNumber: 'PB65IJ3456',
    type: 'SUV',
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    seats: 5,
    doors: 5,
    baggageCapacity: 4,
    mileage: 22400,
    fuelCapacityLiters: 50,
    currentFuelPercent: 88,
    locationId: 'loc_khr_1',
    location: mockLocations[1],
    pricing: {
      daily: 3800,
      weekly: 24000,
      monthly: 88000,
      extraKmCharge: 18,
      freeKmPerDay: 300,
    },
    securityDeposit: 8000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Panoramic Sunroof', 'Ventilated Front Seats', 'Hill Start Assist', 'Bose 8-Speaker Audio'],
    color: 'Abyss Black',
    averageRating: 4.9,
    reviewCount: 42,
  },
  {
    _id: 'veh_5',
    make: 'Toyota',
    model: 'Innova Crysta',
    variant: 'ZX 7-Seater',
    year: 2023,
    registrationNumber: 'CH01EF5678',
    type: 'MUV',
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    seats: 7,
    doors: 5,
    baggageCapacity: 5,
    mileage: 31000,
    fuelCapacityLiters: 55,
    currentFuelPercent: 92,
    locationId: 'loc_chd_1',
    location: mockLocations[0],
    pricing: {
      daily: 4800,
      weekly: 30000,
      monthly: 110000,
      extraKmCharge: 20,
      freeKmPerDay: 300,
    },
    securityDeposit: 10000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Captain Seats 2nd Row', 'Rear AC with Controls', '7 Airbags', 'Cruise Control', 'Extra Luggage Rack'],
    color: 'Super White',
    averageRating: 4.8,
    reviewCount: 38,
  },
  {
    _id: 'veh_6',
    make: 'Honda',
    model: 'City',
    variant: 'ZX',
    year: 2024,
    registrationNumber: 'CH01CD3456',
    type: 'SEDAN',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    seats: 5,
    doors: 4,
    baggageCapacity: 3,
    mileage: 9600,
    fuelCapacityLiters: 40,
    currentFuelPercent: 100,
    locationId: 'loc_chd_1',
    location: mockLocations[0],
    pricing: {
      daily: 3200,
      weekly: 20000,
      monthly: 74000,
      extraKmCharge: 16,
      freeKmPerDay: 300,
    },
    securityDeposit: 7000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Lane Watch Camera', 'ADAS Safety Tech', 'Sunroof', 'Leather Upholstery', 'Paddle Shifters'],
    color: 'Golden Brown Metallic',
    averageRating: 5.0,
    reviewCount: 22,
  },
  {
    _id: 'veh_7',
    make: 'Mahindra',
    model: 'Scorpio-N',
    variant: 'Z8L 4x4',
    year: 2024,
    registrationNumber: 'PB65IJ4567',
    type: 'SUV',
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    seats: 7,
    doors: 5,
    baggageCapacity: 4,
    mileage: 14200,
    fuelCapacityLiters: 57,
    currentFuelPercent: 90,
    locationId: 'loc_khr_1',
    location: mockLocations[1],
    pricing: {
      daily: 4500,
      weekly: 28000,
      monthly: 105000,
      extraKmCharge: 18,
      freeKmPerDay: 250,
    },
    securityDeposit: 10000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['4XPLOR Intelligent Terrain Modes', 'Sony 12-Speaker 3D Immersive Sound', 'Wireless Android Auto', 'Hill Descent'],
    color: 'Deep Forest Green',
    averageRating: 4.9,
    reviewCount: 31,
  },
  {
    _id: 'veh_8',
    make: 'BMW',
    model: '3 Series Gran Limousine',
    variant: '330Li M Sport',
    year: 2024,
    registrationNumber: 'CH01KL6789',
    type: 'LUXURY',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    seats: 5,
    doors: 4,
    baggageCapacity: 3,
    mileage: 6400,
    fuelCapacityLiters: 59,
    currentFuelPercent: 100,
    locationId: 'loc_chd_1',
    location: mockLocations[0],
    pricing: {
      daily: 9500,
      weekly: 60000,
      monthly: 220000,
      extraKmCharge: 35,
      freeKmPerDay: 200,
    },
    securityDeposit: 25000,
    status: 'AVAILABLE',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&w=800&q=80',
    ],
    features: ['Harman Kardon Surround', 'Panoramic Glass Roof', 'Curved Display Screen', 'Parking Assistant Plus'],
    color: 'Portimao Blue',
    averageRating: 5.0,
    reviewCount: 15,
  }
];

export const mockAddOns = [
  {
    _id: 'addon_1',
    name: 'Child Safety Seat',
    description: 'ISOFIX rear-facing or toddler booster seat for young travelers.',
    price: 150,
    pricingType: 'PER_DAY',
    maxQuantity: 2,
  },
  {
    _id: 'addon_2',
    name: 'Dedicated GPS Navigator',
    description: 'Garmin offline satellite GPS preloaded with Himachal & Punjab routes.',
    price: 300,
    pricingType: 'PER_RENTAL',
    maxQuantity: 1,
  },
  {
    _id: 'addon_3',
    name: 'Additional Co-Driver',
    description: 'Authorize a second driver (e.g. college batchmate) with full insurance coverage.',
    price: 500,
    pricingType: 'PER_RENTAL',
    maxQuantity: 2,
  },
  {
    _id: 'addon_4',
    name: 'Roadside Assistance Plus (Hill Cover)',
    description: '24x7 breakdown support on NH-05, Kalka-Shimla highway & tricity roads.',
    price: 400,
    pricingType: 'PER_RENTAL',
    maxQuantity: 1,
  },
  {
    _id: 'addon_5',
    name: 'Fuel Prepay Option',
    description: 'Return on empty! Refueled at pump rates with zero convenience fee.',
    price: 1200,
    pricingType: 'PER_RENTAL',
    maxQuantity: 1,
  },
];

export const mockCoupons = [
  {
    _id: 'coup_1',
    code: 'CU10',
    type: 'PERCENTAGE',
    value: 10,
    maximumDiscount: 1500,
    minimumRental: 1500,
    description: '10% Exclusive Discount for Chandigarh University (CU) Students (Valid Student ID Required)',
    active: true,
  },
  {
    _id: 'coup_2',
    code: 'WEEKEND10',
    type: 'PERCENTAGE',
    value: 10,
    maximumDiscount: 1500,
    minimumRental: 2000,
    description: '10% off up to ₹1,500 on weekend rentals',
    active: true,
  },
];

export const mockDemoUsers = {
  customer: {
    _id: 'user_cust_1',
    name: 'Neha Sharma (CU Student)',
    email: 'neha@example.com',
    phone: '+91 98765 10001',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    token: 'mock_jwt_customer',
    university: 'Chandigarh University',
  },
  owner: {
    _id: 'user_owner_1',
    name: 'Aarav Mehta',
    email: 'owner@example.com',
    phone: '+91 98765 00001',
    role: 'OWNER',
    status: 'ACTIVE',
    token: 'mock_jwt_owner',
  },
  manager: {
    _id: 'user_mgr_1',
    name: 'Priya Nair (Chandigarh Hub)',
    email: 'priya.manager@driveeasy.example',
    phone: '+91 98765 00002',
    role: 'MANAGER',
    assignedLocation: 'loc_chd_1',
    status: 'ACTIVE',
    token: 'mock_jwt_manager',
  },
  staff: {
    _id: 'user_staff_1',
    name: 'Sana Khan (Kharar / CU Hub)',
    email: 'sana.staff@driveeasy.example',
    phone: '+91 98765 00004',
    role: 'STAFF',
    assignedLocation: 'loc_khr_1',
    status: 'ACTIVE',
    token: 'mock_jwt_staff',
  },
  accountant: {
    _id: 'user_acct_1',
    name: 'Vikram Rao',
    email: 'vikram.accounts@driveeasy.example',
    phone: '+91 98765 00005',
    role: 'ACCOUNTANT',
    status: 'ACTIVE',
    token: 'mock_jwt_accountant',
  },
};

export const mockBookings = [
  {
    _id: 'bk_1',
    bookingNumber: 'CR-2026-000101',
    customerId: 'user_cust_1',
    customer: mockDemoUsers.customer,
    vehicleId: 'veh_3',
    vehicle: mockVehicles[2], // Thar
    locationId: 'loc_khr_1',
    location: mockLocations[1], // Kharar - CU Hub
    pickupDate: '2026-09-12T10:00:00.000Z',
    returnDate: '2026-09-15T10:00:00.000Z',
    pickupTime: '10:00',
    returnTime: '10:00',
    startAt: '2026-09-12T10:00:00.000Z',
    endAt: '2026-09-15T10:00:00.000Z',
    status: 'CONFIRMED',
    pricingBreakdown: {
      days: 3,
      base: 12600,
      addOnsTotal: 400,
      subtotal: 13000,
      discount: 1300, // 10% CU Student discount
      tax: 2106,
      securityDeposit: 10000,
      total: 13806,
    },
    totalAmount: 13806,
    amountPaid: 13806,
    paymentStatus: 'PAID',
    couponCode: 'CU10',
    createdAt: '2026-09-08T14:20:00.000Z',
  },
  {
    _id: 'bk_2',
    bookingNumber: 'CR-2026-000098',
    customerId: 'user_cust_1',
    customer: mockDemoUsers.customer,
    vehicleId: 'veh_1',
    vehicle: mockVehicles[0], // Swift
    locationId: 'loc_chd_1',
    location: mockLocations[0], // Chandigarh
    pickupDate: '2026-09-02T10:00:00.000Z',
    returnDate: '2026-09-04T10:00:00.000Z',
    pickupTime: '10:00',
    returnTime: '10:00',
    startAt: '2026-09-02T10:00:00.000Z',
    endAt: '2026-09-04T10:00:00.000Z',
    status: 'COMPLETED',
    pricingBreakdown: {
      days: 2,
      base: 3600,
      addOnsTotal: 0,
      subtotal: 3600,
      discount: 360,
      tax: 583,
      securityDeposit: 4000,
      total: 3823,
    },
    totalAmount: 3823,
    amountPaid: 3823,
    paymentStatus: 'PAID',
    couponCode: 'CU10',
    createdAt: '2026-08-30T09:15:00.000Z',
  },
];

export const mockDashboardStats = {
  grossRevenue: 512400,
  activeBookings: 9,
  pendingBookings: 2,
  fleetUtilization: 84.2,
  totalVehicles: 12,
  availableVehicles: 8,
  rentedVehicles: 3,
  maintenanceVehicles: 1,
  pickupsToday: 5,
  returnsToday: 4,
  pendingKyc: 2,
};

export const mockMaintenanceAlerts = [
  {
    _id: 'maint_1',
    vehicle: mockVehicles[0],
    type: 'SERVICE',
    title: '15,000 km Scheduled Service Due',
    dueDate: '2026-09-22',
    status: 'SCHEDULED',
    priority: 'HIGH',
    cost: 4200,
  },
  {
    _id: 'maint_2',
    vehicle: mockVehicles[2],
    type: 'PUC',
    title: 'Punjab PUC Emission Certificate Renewal',
    dueDate: '2026-09-28',
    status: 'SCHEDULED',
    priority: 'MEDIUM',
    cost: 150,
  },
];

export const mockCustomerReviews = [
  {
    _id: 'rev_1',
    author: 'Amanpreet Singh',
    rating: 5,
    date: '2 days ago',
    car: 'Mahindra Thar 4x4',
    title: 'Awesome CU student road trip to Kasauli!',
    comment: 'Booked the Thar from the Kharar CU hub. Handover took 3 minutes right outside campus gate. The 10% student discount made the trip super affordable split between 4 friends!',
    verified: true,
  },
  {
    _id: 'rev_2',
    author: 'Neha Sharma',
    rating: 5,
    date: '1 week ago',
    car: 'Maruti Swift VXI',
    title: 'Super smooth drive around Chandigarh & Mohali',
    comment: 'Pristine car, working Fastag, and transparent rates. The security deposit was credited back to my UPI within 2 hours after return at Sector 17.',
    verified: true,
  },
  {
    _id: 'rev_3',
    author: 'Sahil Gulati',
    rating: 5,
    date: '2 weeks ago',
    car: 'Hyundai Creta SX',
    title: 'Reliable highway vehicle for family trip to Shimla',
    comment: 'Diesel automatic Creta had immense power for the Himalayan expressway slopes. 100% sanitized with spotless interiors.',
    verified: true,
  },
];
