export const ROLES = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  ACCOUNTANT: 'ACCOUNTANT',
  CUSTOMER: 'CUSTOMER',
};

export const STAFF_ROLES = [
  ROLES.OWNER,
  ROLES.MANAGER,
  ROLES.STAFF,
  ROLES.ACCOUNTANT,
];

export const VEHICLE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BOOKED: 'BOOKED',
  RENTED: 'RENTED',
  MAINTENANCE: 'MAINTENANCE',
  RESERVED: 'RESERVED',
  INACTIVE: 'INACTIVE',
};

export const VEHICLE_TYPE = {
  HATCHBACK: 'HATCHBACK',
  SEDAN: 'SEDAN',
  SUV: 'SUV',
  MUV: 'MUV',
  LUXURY: 'LUXURY',
  VAN: 'VAN',
};

export const TRANSMISSION = {
  MANUAL: 'MANUAL',
  AUTOMATIC: 'AUTOMATIC',
};

export const FUEL_TYPE = {
  PETROL: 'PETROL',
  DIESEL: 'DIESEL',
  ELECTRIC: 'ELECTRIC',
  HYBRID: 'HYBRID',
  CNG: 'CNG',
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

export const PAYMENT_KIND = {
  RENTAL: 'RENTAL',
  DEPOSIT: 'DEPOSIT',
  DEPOSIT_REFUND: 'DEPOSIT_REFUND',
  EXTRA_CHARGES: 'EXTRA_CHARGES',
  REFUND: 'REFUND',
};

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  CARD: 'CARD',
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER',
  ONLINE: 'ONLINE',
  OTHER: 'OTHER',
};

export const INSPECTION_TYPE = {
  PICKUP: 'PICKUP',
  RETURN: 'RETURN',
};

export const CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  POOR: 'POOR',
};

export const DAMAGE_SEVERITY = {
  MINOR: 'MINOR',
  MODERATE: 'MODERATE',
  SEVERE: 'SEVERE',
};

export const DAMAGE_STATUS = {
  REPORTED: 'REPORTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REPAIRING: 'REPAIRING',
  RESOLVED: 'RESOLVED',
};

export const MAINTENANCE_TYPE = {
  SERVICE: 'SERVICE',
  OIL_CHANGE: 'OIL_CHANGE',
  TYRE_REPLACEMENT: 'TYRE_REPLACEMENT',
  BRAKE_SERVICE: 'BRAKE_SERVICE',
  REPAIR: 'REPAIR',
  INSURANCE: 'INSURANCE',
  PUC: 'PUC',
  OTHER: 'OTHER',
};

export const MAINTENANCE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const DOCUMENT_TYPE = {
  DRIVING_LICENCE: 'DRIVING_LICENCE',
  GOVERNMENT_ID: 'GOVERNMENT_ID',
  OTHER: 'OTHER',
};

export const DOCUMENT_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const COUPON_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
};

export const EMERGENCY_TYPE = {
  BREAKDOWN: 'BREAKDOWN',
  FLAT_TYRE: 'FLAT_TYRE',
  ACCIDENT: 'ACCIDENT',
  BATTERY: 'BATTERY',
  LOCKED_OUT: 'LOCKED_OUT',
  OTHER: 'OTHER',
};

export const EMERGENCY_STATUS = {
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};
